services:
  - type: web
    name: online-shop
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn djangoProject.wsgi:application
