# Generated by Django 5.1 on 2024-11-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_module", "0003_slider_alter_footerlink_footer_link_box"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال | غیر فعال"),
        ),
    ]
