# Generated by Django 5.1 on 2024-11-14 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="عنوان دسته بندی"),
                ),
                (
                    "url_title",
                    models.CharField(max_length=100, verbose_name="عنوان url"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال|غیر فعال"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="article_module.articlecategory",
                        verbose_name="والد محصولات",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته بندی مقاله",
                "verbose_name_plural": "دسته بندی های مقاله",
            },
        ),
    ]
