# Generated by Django 5.1 on 2024-11-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_module", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان مقاله")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, max_length=400, verbose_name="عنوان در url"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/articles", verbose_name="تصویر مقاله"
                    ),
                ),
                ("short_description", models.TextField(verbose_name="توضیحات کوتاه")),
                ("text", models.TextField(verbose_name="متن مقاله")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال / غیرفعال"),
                ),
                (
                    "selected_categories",
                    models.ManyToManyField(
                        to="article_module.articlecategory", verbose_name="دسته بندی ها"
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات",
            },
        ),
    ]
