# Generated by Django 5.1 on 2024-11-19 10:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_module", "0003_article_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="create_data",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.date(2024, 11, 19),
                verbose_name="تاریخ ثبت",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="نویسنده",
            ),
        ),
    ]
