# Generated by Django 5.1 on 2025-12-23 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_module", "0006_alter_articlecomment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlecategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_categories",
                to="article_module.articlecategory",
                verbose_name="والد محصولات",
            ),
        ),
    ]
