# Generated by Django 5.1 on 2025-02-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="آدرس"),
        ),
    ]
