# Generated by Django 5.1 on 2025-07-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0007_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
